### ISSUE TITLE
q2q.py do what

### ISSUE THREAD

**Issue by xilinniao123** [ypeng7/PY-NLP#1]
thanks for sharing.
now i want to do something related to triplet loss in nlp.
 i want to ask q2q.py do what? is there any paper related?

**Comment by xilinniao123** [comment]
can you share dome line of your data data_sample_132.csv

**Comment by yuepaang** [comment]
> can you share dome line of your data data_sample_132.csv

basically "q2q" means question to question, it was a text classification model.

Input data is simple csv file, like

query,label
Hello world, 0

Hope this can help.
Thanks
